name: Build & Deploy
on:
  # Trigger auto sync only for changes on main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Login to BIA and sync plugin
    runs-on: ubuntu-18.04
    steps:
      - name: SSH into BIA and git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BIA_SITE_URL }}
          username: ${{ secrets.BIA_USER }}
          key: ${{ secrets.BIA_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/public_html/wp-content/plugins/bia-delivery
            git pull
