name: Build & Deploy
on:
  # Trigger auto sync only for changes on main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Login to BIA and sync plugin
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
      - name: Create SSH key
        with:
          host: ${{ secrets.BIA_SITE_URL }}
          username: ${{ secrets.BIA_USER }}
          password: ""
          port: 22
          script: |            
            cd ~/public_html/wp-content/plugins/bia-delivery
            git pull
        
